services:
  mysql: 
    image: "mysql:5.7"
    container_name: mysql-mycrud
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: mypass
      MYSQL_DATABASE: my_crud
    volumes:
      - ./docker-config/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - ./backend/database:/var/lib/mysql
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=mypass --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 30s
      retries: 3
      start_period: 20s

  app:
    image: "node:17-slim"
    build: "./backend/app.js"
    container_name: api-mycrud
    working_dir: /application/app
    entrypoint: /application/app/start_application.sh
    volumes:
      - ./backend:/application/app
      - ./docker-config/node/start_application.sh:/application/app/start_application.sh
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    healthcheck:
      test: "wget --no-verbose --tries=1 --spider http://localhost:8000 || exit 1"
      interval: 60s
      timeout: 30s
      retries: 3
      start_period: 20s

  web:
    image: "nginx:1.20.2"
    container_name: nginx-mycrud
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./docker-config/nginx/default.conf:/etc/nginx/default.conf
    ports:
      - "80:80"
    depends_on:
      - app
    healthcheck:
      test: "wget --no-verbose --tries=1 --spider http://localhost:80 || exit 1"
      interval: 60s
      timeout: 30s
      retries: 3
      start_period: 20s


